/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksimulator;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.*;

/**
 *
 * @author deshm
 */
public class AccountDetails extends javax.swing.JFrame {

    /**
     * Creates new form AccountDetails
     */
    long id,cardno,pin;
    public AccountDetails(long r) {
        Random ran1 = new Random();
        cardno = Math.abs(ran1.nextLong() % 9000000000L) + 1000000000L;
        pin = Math.abs(ran1.nextLong() % 9000L) + 1000L;
        
        initComponents();
        lblcardno.setText("XXX-XXX-"+(cardno%10000));
        lblpin.setText("XXXX");
        id = r;
        String str = "Form No.:"+id;
        lblformno.setText(str);
        addImageToLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblformno = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnfixeddeposit = new javax.swing.JRadioButton();
        btnsaving = new javax.swing.JRadioButton();
        btnrecurring = new javax.swing.JRadioButton();
        btncurrent = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lblcardno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblpin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btninternet = new javax.swing.JRadioButton();
        btnatm = new javax.swing.JRadioButton();
        btnemail = new javax.swing.JRadioButton();
        btnmobilebanking = new javax.swing.JRadioButton();
        btncheckbook = new javax.swing.JRadioButton();
        btnestatement = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGNUP");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Page 3 : Account Details");

        lblformno.setBackground(new java.awt.Color(255, 255, 255));
        lblformno.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lblformno.setForeground(new java.awt.Color(0, 0, 0));
        lblformno.setText("jLabel2");

        lblLogo.setForeground(new java.awt.Color(0, 0, 0));
        lblLogo.setText("jLabel3");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Account Type");

        btnfixeddeposit.setBackground(new java.awt.Color(255, 255, 255));
        btnfixeddeposit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnfixeddeposit.setForeground(new java.awt.Color(0, 0, 0));
        btnfixeddeposit.setText(" Fixed Deposit Account");
        btnfixeddeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfixeddepositActionPerformed(evt);
            }
        });

        btnsaving.setBackground(new java.awt.Color(255, 255, 255));
        btnsaving.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnsaving.setForeground(new java.awt.Color(0, 0, 0));
        btnsaving.setText(" Saving Account");

        btnrecurring.setBackground(new java.awt.Color(255, 255, 255));
        btnrecurring.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnrecurring.setForeground(new java.awt.Color(0, 0, 0));
        btnrecurring.setText(" Recurring Deposit Account");
        btnrecurring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecurringActionPerformed(evt);
            }
        });

        btncurrent.setBackground(new java.awt.Color(255, 255, 255));
        btncurrent.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btncurrent.setForeground(new java.awt.Color(0, 0, 0));
        btncurrent.setText(" Current Account");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Card Number : ");

        lblcardno.setBackground(new java.awt.Color(255, 255, 255));
        lblcardno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblcardno.setForeground(new java.awt.Color(0, 0, 0));
        lblcardno.setText("jLabel4");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PIN : ");

        lblpin.setBackground(new java.awt.Color(255, 255, 255));
        lblpin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblpin.setForeground(new java.awt.Color(0, 0, 0));
        lblpin.setText("jLabel4");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Services Required ");

        btninternet.setBackground(new java.awt.Color(255, 255, 255));
        btninternet.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btninternet.setForeground(new java.awt.Color(0, 0, 0));
        btninternet.setText("Internet Banking");

        btnatm.setBackground(new java.awt.Color(255, 255, 255));
        btnatm.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnatm.setForeground(new java.awt.Color(0, 0, 0));
        btnatm.setText("ATM Card");

        btnemail.setBackground(new java.awt.Color(255, 255, 255));
        btnemail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnemail.setForeground(new java.awt.Color(0, 0, 0));
        btnemail.setText("Email Alert");

        btnmobilebanking.setBackground(new java.awt.Color(255, 255, 255));
        btnmobilebanking.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnmobilebanking.setForeground(new java.awt.Color(0, 0, 0));
        btnmobilebanking.setText("Mobile Banking");

        btncheckbook.setBackground(new java.awt.Color(255, 255, 255));
        btncheckbook.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btncheckbook.setForeground(new java.awt.Color(0, 0, 0));
        btncheckbook.setText("Check Book");

        btnestatement.setBackground(new java.awt.Color(255, 255, 255));
        btnestatement.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnestatement.setForeground(new java.awt.Color(0, 0, 0));
        btnestatement.setText("E-Statement");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("I hereby confirm information provided is True and valid");
        jCheckBox1.setInheritsPopupMenu(true);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblformno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblcardno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btncurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnsaving, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(119, 119, 119)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnfixeddeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnrecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnatm, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnmobilebanking, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btncheckbook, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnemail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnestatement, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btninternet, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(52, 52, 52)))
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblformno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsaving, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfixeddeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcardno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninternet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnatm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnemail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmobilebanking, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncheckbook, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnestatement, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jCheckBox1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnfixeddepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfixeddepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfixeddepositActionPerformed

    private void btnrecurringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecurringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrecurringActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String accounttype = "";
        if(btnsaving.isSelected()==false && btncurrent.isSelected()==false && btnrecurring.isSelected() == false && btnfixeddeposit.isSelected()==false)
        {
            JOptionPane.showMessageDialog(this, "Enter the account type");
            return;
        }
        if(btnsaving.isSelected())
        {
            accounttype = "Saving account";
        }
        else if(btncurrent.isSelected())
        {
            accounttype = "Current account";
        }
        else if(btnfixeddeposit.isSelected())
        {
            accounttype = "Fixed Deposit account";
        }
        else if(btnrecurring.isSelected())
        {
            accounttype = "Recurring deposit account";
        }
        String services ="";
        if(btnatm.isSelected() == false && btninternet.isSelected() == false && btnemail.isSelected() == false && btnestatement.isSelected() == false && btncheckbook.isSelected() == false && btnmobilebanking.isSelected() == false)
        {
            JOptionPane.showMessageDialog(this, "Enter the Services");
            return;
        }
        if(btnatm.isSelected())
        {
            services = services + "ATM card"+" ";
        }
        if(btninternet.isSelected())
        {
            services = services + "Internet Banking"+" ";
        }
        if(btnmobilebanking.isSelected())
        {
            services = services + "Mobile Banking"+" ";
        }
        if(btnemail.isSelected())
        {
            services = services + "Email alert"+" ";
        }
        if(btncheckbook.isSelected())
        {
            services = services + "Checkbook"+" ";
        }
        if(btnestatement.isSelected())
        {
            services = services + "E-statement"+" ";
        }
        try
        {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","sa123");
            Statement st = c.createStatement();
            String query = "insert into signup3 values ("+id+" , '"+accounttype+"' , '"+services+"');";
            String query2 = "insert into login values ("+id+" , "+cardno+" , "+pin+" );";
            st.executeUpdate(query);
            st.executeUpdate(query2);
            
            JOptionPane.showMessageDialog(this, "Card Number : "+cardno+"\nPIN : "+pin);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        String i = "";
        i = i+id;
        new Deposit(i).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private void addImageToLabel()
    {
        BufferedImage img;
        try
        {
            img = ImageIO.read(new File("C:\\Users\\deshm\\Downloads\\Bank.jpeg"));
            Image dimg = img.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageicon = new ImageIcon(dimg);
            lblLogo.setIcon(imageicon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnatm;
    private javax.swing.JRadioButton btncheckbook;
    private javax.swing.JRadioButton btncurrent;
    private javax.swing.JRadioButton btnemail;
    private javax.swing.JRadioButton btnestatement;
    private javax.swing.JRadioButton btnfixeddeposit;
    private javax.swing.JRadioButton btninternet;
    private javax.swing.JRadioButton btnmobilebanking;
    private javax.swing.JRadioButton btnrecurring;
    private javax.swing.JRadioButton btnsaving;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblcardno;
    private javax.swing.JLabel lblformno;
    private javax.swing.JLabel lblpin;
    // End of variables declaration//GEN-END:variables
}
