/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksimulator;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
/**
 *
 * @author deshm
 */
public class MiniStatement extends javax.swing.JFrame {

    /**
     * Creates new form MiniStatement
     */
    String id;
    public MiniStatement(String i) {
        initComponents();
        id = i;
        lbltransection.setBorder(null);
        try
            {
                int amount=0;
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","sa123");
                Statement st = c.createStatement();
                String query = "select * from transection where id = "+id+" ; ";
                ResultSet rs = st.executeQuery(query);
                int counter=0;
                if(rs.next())
                {
                    amount = Integer.parseInt(rs.getString("amount"));
                    lbltransection.setText(rs.getString("date")+"    "+rs.getString("depositandwithdraw"));
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "You Don't have any transection");
                    return;
                }
                counter++;
                while(true)
                {
                    if(rs.next())
                    {
                        amount = Integer.parseInt(rs.getString("amount"));
                        counter++;
                    }
                    else
                    {
                        break;
                    }
                }
                lblbalance.setText("Your current account balance is "+amount);
                rs = st.executeQuery(query);
                lbltransection.setText(" ");
                String s = " ";
                if(counter<=5)
                {
                    while(rs.next())
                    {
                        s=rs.getString("date")+"                               "+rs.getString("depositandwithdraw")+"\n"+lbltransection.getText();
                        lbltransection.setText(s);
                    }
                }
                else
                {
                    int c1 = counter-6;
                    while(rs.next() && c1!=0)
                    {
                        c1--;
                    }
                    while(rs.next())
                    {
                        s=rs.getString("date")+"                               "+rs.getString("depositandwithdraw")+"\n\n";
                        s = s+lbltransection.getText();
                        lbltransection.setText(s);
                    }
                }
                query = "select * from login where id = "+id+";";
                rs = st.executeQuery(query);
                rs.next();
                lblcard.setText("Card No. : XXX XXX "+rs.getString("cardno").substring(6));
            
            }
            catch(Exception ex)
            {
                System.out.println(ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblbalance = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbltransection = new javax.swing.JTextArea();
        lblcard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mini Statement");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Universal Bank");

        lblbalance.setBackground(new java.awt.Color(255, 255, 255));
        lblbalance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblbalance.setForeground(new java.awt.Color(0, 0, 0));

        lbltransection.setEditable(false);
        lbltransection.setBackground(new java.awt.Color(255, 255, 255));
        lbltransection.setColumns(20);
        lbltransection.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbltransection.setForeground(new java.awt.Color(0, 0, 0));
        lbltransection.setRows(5);
        lbltransection.setBorder(null);
        lbltransection.setFocusable(false);
        jScrollPane1.setViewportView(lbltransection);

        lblcard.setBackground(new java.awt.Color(255, 255, 255));
        lblcard.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblcard.setForeground(new java.awt.Color(0, 0, 0));
        lblcard.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcard, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblcard, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lblbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new MiniStatement("9992").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblcard;
    private javax.swing.JTextArea lbltransection;
    // End of variables declaration//GEN-END:variables
}
