/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksimulator;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author deshm
 */
public class Pinchange extends javax.swing.JFrame implements ActionListener,KeyListener {

    /**
     * Creates new form Pinchange
     */
    String id;
    JPasswordField txtnew,txtconfirm;
    JButton btndeposit,btncancel;
    public Pinchange(String i) {
        id = i;
        initComponents();
        addImageToLabel();
        
        JLabel l1 = new JLabel("Enter New Password : ");
        l1.setBounds(135, 260, 300, 22);
        l1.setForeground(Color.WHITE);
        l1.setFont(new Font("System",Font.BOLD,16));
        lblLogo.add(l1);
        
        txtnew = new JPasswordField("");
        txtnew.setBounds(135, 285, 290, 22);
        txtnew.setBackground(Color.WHITE);
        txtnew.setForeground(Color.BLACK);
        txtnew.setFont(new Font("System",Font.BOLD,16));
        lblLogo.add(txtnew);
        txtnew.addKeyListener(this);
        
        JLabel l2 = new JLabel("Enter Confirm New Password : ");
        l2.setBounds(135, 310, 300, 22);
        l2.setForeground(Color.WHITE);
        l2.setFont(new Font("System",Font.BOLD,16));
        lblLogo.add(l2);
        
        txtconfirm = new JPasswordField("");
        txtconfirm.setBounds(135, 335, 290, 22);
        txtconfirm.setBackground(Color.WHITE);
        txtconfirm.setForeground(Color.BLACK);
        txtconfirm.setFont(new Font("System",Font.BOLD,16));
        lblLogo.add(txtconfirm);
        txtconfirm.addKeyListener(this);
        
        btndeposit = new JButton("Submit");
        btndeposit.setBounds(310, 400, 100, 40);
        btndeposit.setBackground(Color.WHITE);
        btndeposit.setForeground(Color.BLACK);
        btndeposit.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btndeposit);
        btndeposit.addActionListener(this);

        btncancel = new JButton("Cancel");
        btncancel.setBounds(140, 400, 100, 40);
        btncancel.setBackground(Color.WHITE);
        btncancel.setForeground(Color.BLACK);
        btncancel.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btncancel);
        btncancel.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void addImageToLabel()
    {
        BufferedImage img;
        try
        {
            img = ImageIO.read(new File("C:\\Users\\deshm\\Downloads\\atm2.jpeg"));
            Image dimg = img.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageicon = new ImageIcon(dimg);
            lblLogo.setIcon(imageicon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pinchange");
        setUndecorated(true);

        lblLogo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Pinchange("9992").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(e.getSource() == btncancel)
        {
            new Transection(id).setVisible(true);
            this.dispose();
        }
        if(e.getSource() == btndeposit)
        {
            int n,c1;
            n = Integer.parseInt(new String(txtnew.getPassword()));
            c1 = Integer.parseInt(new String(txtconfirm.getPassword()));
            System.out.println(n);
            System.out.println(c1);
            if(n!=c1)
            {
                JOptionPane.showMessageDialog(this, "New and Confirm password doesn't match");
                txtnew.setText("");
                txtconfirm.setText("");
                return;
            }
            
            try
            {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","sa123");
                Statement st = c.createStatement();
                String query = "update login set pin = "+c1+" where id = "+id+" ; ";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Updated Successfully");
                new Transection(id).setVisible(true);
                this.dispose();

            }
            catch(Exception e1)
            {
                JOptionPane.showMessageDialog(this, e1);
            }
        }
    }

    @Override
    public void keyTyped(KeyEvent evt) {
        
        if(evt.getSource() == txtnew)
        {
            char ch;
        ch = evt.getKeyChar();
        if(Character.isDigit(ch) == false)
        {
            evt.consume();
        }
        String str = new String(txtnew.getPassword());
        if(str.length() > 3)
        {
            evt.consume();
        }
        }
        if(evt.getSource() == txtconfirm)
        {
            char ch;
        ch = evt.getKeyChar();
        if(Character.isDigit(ch) == false)
        {
            evt.consume();
        }
        String str = new String(txtconfirm.getPassword());
        if(str.length() > 3)
        {
            evt.consume();
        }
        }
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
