/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banksimulator;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.*;
/**
 *
 * @author deshm
 */
public class Transection extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Transection
     */
    JButton btndeposit,btnwithdraw,btnfastcash,btnpinchange,btnministatement,btnbalanceenquiry,btnexit;
    String id;
    public Transection(String i) {
        initComponents();
        id=i;
        addImageToLabel();
        
        JLabel l1 = new JLabel("Please select your Transection");
        l1.setBounds(160, 250, 300, 22);
        l1.setForeground(Color.WHITE);
        l1.setFont(new Font("System",Font.BOLD,16));
        lblLogo.add(l1);
        
        btndeposit = new JButton("Deposit");
        btndeposit.setBounds(140, 300, 140, 40);
        btndeposit.setBackground(Color.WHITE);
        btndeposit.setForeground(Color.BLACK);
        btndeposit.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btndeposit);
        btndeposit.addActionListener(this);
        
        btnwithdraw = new JButton("Cash Withdraw");
        btnwithdraw.setBounds(280, 300, 140, 40);
        btnwithdraw.setBackground(Color.WHITE);
        btnwithdraw.setForeground(Color.BLACK);
        btnwithdraw.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btnwithdraw);
        btnwithdraw.addActionListener(this);
        
        btnfastcash = new JButton("Fast Cash");
        btnfastcash.setBounds(140, 340, 140, 40);
        btnfastcash.setBackground(Color.WHITE);
        btnfastcash.setForeground(Color.BLACK);
        btnfastcash.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btnfastcash);
        btnfastcash.addActionListener(this);
        
        btnpinchange = new JButton("Pin Change");
        btnpinchange.setBounds(280, 340, 140, 40);
        btnpinchange.setBackground(Color.WHITE);
        btnpinchange.setForeground(Color.BLACK);
        btnpinchange.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btnpinchange);
        btnpinchange.addActionListener(this);
        
        btnministatement = new JButton("Mini Statement");
        btnministatement.setBounds(280, 380, 140, 40);
        btnministatement.setBackground(Color.WHITE);
        btnministatement.setForeground(Color.BLACK);
        btnministatement.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btnministatement);
        btnministatement.addActionListener(this);
        
        btnbalanceenquiry = new JButton("Balance Enquiry");
        btnbalanceenquiry.setBounds(140, 380, 140, 40);
        btnbalanceenquiry.setBackground(Color.WHITE);
        btnbalanceenquiry.setForeground(Color.BLACK);
        btnbalanceenquiry.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btnbalanceenquiry);
        btnbalanceenquiry.addActionListener(this);
        
        btnexit = new JButton("EXIT");
        btnexit.setBounds(280, 440, 140, 40);
        btnexit.setBackground(Color.WHITE);
        btnexit.setForeground(Color.BLACK);
        btnexit.setFont(new Font("System",Font.BOLD,14));
        lblLogo.add(btnexit);
        btnexit.addActionListener(this);
    }
            
    private void addImageToLabel()
    {
        BufferedImage img;
        try
        {
            img = ImageIO.read(new File("C:\\Users\\deshm\\Downloads\\atm2.jpeg"));
            Image dimg = img.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageicon = new ImageIcon(dimg);
            lblLogo.setIcon(imageicon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transection");
        setUndecorated(true);

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Transection("9992").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        
        if(e.getSource() == btnexit)
        {
            this.dispose();
        }
        if(e.getSource() == btndeposit)
        {
            new Deposit(id).setVisible(true);
            this.dispose();
        }
        if(e.getSource() == btnwithdraw)
        {
            new Withdraw(id).setVisible(true);
            this.dispose();
        }
        if(e.getSource() == btnfastcash)
        {
            new FastCash(id).setVisible(true);
            this.dispose();
        }
        if(e.getSource() == btnbalanceenquiry)
        {
            new BalanceEnquiry(id).setVisible(true);
            this.dispose();
        }
        if(e.getSource() == btnpinchange)
        {
            new Pinchange(id).setVisible(true);
            this.dispose();
        }
        if(e.getSource() == btnministatement)
        {
            new MiniStatement(id).setVisible(true);
            
        }
    }
}
